### ISSUE TITLE
I am getting these errors on a test environment with OVS monitoring

### ISSUE THREAD

**Issue by kinvaris** [openvstorage/openvstorage-monitoring#50]
```
2016-07-27 14:41:54 87700 +0200 - cmp03 - 23287/139935966398272 - celery/celery.worker.job - 15954 - ERROR - Task statsmonkey.sender.get_backend_sizes[a406087d-c380-4d4f-a2ac-a0cc1e27ca59] 
raised unexpected: AttributeError("'AlbaBackend' object has no attribute 'ns_statistics'",)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/OpenvStorage/ovs/lib/helpers/decorators.py", line 178, in new_function
    output = function(*args, **kwargs)
  File "/opt/OpenvStorage/ovs/lib/statsmonkeyscheduledtask.py", line 106, in get_backend_sizes
    global_size = b.alba_backend.ns_statistics['global']
AttributeError: 'AlbaBackend' object has no attribute 'ns_statistics'
```

**Comment by jeroenmaelbrancke** [comment]
ns_statistics is now called usages. Already solved in PR #54
