### ISSUE TITLE
Statsmonkey error

### ISSUE THREAD

**Issue by wimpers** [openvstorage/openvstorage-monitoring#58]
So this in the logs on the controller of OVH Roubaix

```
Traceback (most recent call last):
  File "/opt/statsmonkey/statsmonkey.py", line 249, in <module>
    monkey.run()
  File "/opt/statsmonkey/statsmonkey.py", line 41, in run
    time.sleep(interval)
TypeError: a float is required
Traceback (most recent call last):
  File "/opt/statsmonkey/statsmonkey.py", line 249, in <module>
    monkey.run()
  File "/opt/statsmonkey/statsmonkey.py", line 41, in run
    time.sleep(interval)
TypeError: a float is required
Traceback (most recent call last):
  File "/opt/statsmonkey/statsmonkey.py", line 249, in <module>
    monkey.run()
  File "/opt/statsmonkey/statsmonkey.py", line 41, in run
    time.sleep(interval)
TypeError: a float is required
Traceback (most recent call last):
  File "/opt/statsmonkey/statsmonkey.py", line 249, in <module>
    monkey.run()
  File "/opt/statsmonkey/statsmonkey.py", line 41, in run
    time.sleep(interval)
TypeError: a float is required
Traceback (most recent call last):
  File "/opt/statsmonkey/statsmonkey.py", line 249, in <module>
    monkey.run()
  File "/opt/statsmonkey/statsmonkey.py", line 41, in run
    time.sleep(interval)
TypeError: a float is required
Traceback (most recent call last):
  File "/opt/statsmonkey/statsmonkey.py", line 249, in <module>
    monkey.run()
  File "/opt/statsmonkey/statsmonkey.py", line 41, in run
    time.sleep(interval)
TypeError: a float is required
Traceback (most recent call last):
  File "/opt/statsmonkey/statsmonkey.py", line 249, in <module>
    monkey.run()
  File "/opt/statsmonkey/statsmonkey.py", line 41, in run
    time.sleep(interval)
TypeError: a float is required

```

**Comment by jeroenmaelbrancke** [comment]
Will be fixed in following PR #60
